# Билд этап
FROM python:3.9-slim AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential

COPY requirements.txt /app

RUN pip install --user -r requirements.txt

COPY . .

# Этап итоговой сборки
FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /app /app
COPY --from=builder /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

EXPOSE 5000

CMD ["python", "app.py"]