version: "3.8"

services:
  web:
    container_name: "my_nginx_container"
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork

  redis:
    container_name:  "my_redis_container"
    image: redis:latest
    networks:
      - mynetwork

  mysql:
    container_name: "my_db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
   mysql_data:

networks:
  mynetwork:
